[project]
name = "pyfad"
version = "1.0.1"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
pydiff = "pyfad.cmdline:pydiff"
pycanon = "pyfad.cmdline:pycanon"

[project.entry-points."pyfad.cmdline"]
pydiff2 = "pyfad.cmdline:pydiff"
