contests:
	python -m contest_cylfit
	python -m contest_norm
	python -m contest_swirl

install-contest-deps:
	pip install https://github.com/aiandit/pycontest/archive/refs/heads/master.zip
	pip install matplotlib
